// ============ SHARED CAR DATA ============
// This file is loaded by both index.html (listings) and car-details.html.
// Later, this will be replaced by real data fetched from your backend/database.

const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2021,
    type: "sale",
    price: 14500,
    mileage: 22000,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "Silver",
    seats: 5,
    description:
      "A reliable, fuel-efficient sedan that's been well maintained with full service history. Great first car or daily commuter.",
    features: ["Backup camera", "Bluetooth", "Cruise control", "Lane assist"],
  },
  {
    id: 2,
    make: "Honda",
    model: "CR-V",
    year: 2022,
    type: "rent",
    price: 45,
    mileage: 9000,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "White",
    seats: 5,
    description:
      "Spacious SUV available for daily or weekly rental. Perfect for road trips or moving larger cargo.",
    features: ["All-wheel drive", "Apple CarPlay", "Sunroof", "Roof rack"],
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    year: 2020,
    type: "sale",
    price: 27800,
    mileage: 18000,
    transmission: "Manual",
    fuel: "Petrol",
    color: "Red",
    seats: 4,
    description:
      "Classic American muscle. V8 engine, manual transmission, well cared for by a single owner.",
    features: ["V8 engine", "Leather seats", "Premium sound system", "Sport mode"],
  },
  {
    id: 4,
    make: "Kia",
    model: "Sportage",
    year: 2023,
    type: "rent",
    price: 55,
    mileage: 4000,
    transmission: "Automatic",
    fuel: "Hybrid",
    color: "Grey",
    seats: 5,
    description:
      "Nearly new hybrid SUV, ideal for longer rentals thanks to excellent fuel economy.",
    features: ["Hybrid engine", "Heated seats", "Wireless charging", "360° camera"],
  },
  {
    id: 5,
    make: "Hyundai",
    model: "Elantra",
    year: 2019,
    type: "sale",
    price: 11200,
    mileage: 41000,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "Blue",
    seats: 5,
    description:
      "Budget-friendly sedan with low running costs. A dependable choice for everyday driving.",
    features: ["Bluetooth", "USB ports", "Keyless entry"],
  },
  {
    id: 6,
    make: "Nissan",
    model: "Rogue",
    year: 2022,
    type: "rent",
    price: 50,
    mileage: 12500,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "Black",
    seats: 5,
    description:
      "Comfortable crossover SUV available for rent, great for families and weekend getaways.",
    features: ["Blind spot warning", "Apple CarPlay", "Third row storage"],
  },
  {
    id: 7,
    make: "Chevrolet",
    model: "Malibu",
    year: 2021,
    type: "sale",
    price: 15900,
    mileage: 27000,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "White",
    seats: 5,
    description:
      "Smooth-riding midsize sedan with a spacious interior and strong safety ratings.",
    features: ["Lane keep assist", "Bluetooth", "Rear camera"],
  },
  {
    id: 8,
    make: "BMW",
    model: "3 Series",
    year: 2020,
    type: "sale",
    price: 24800,
    mileage: 20500,
    transmission: "Automatic",
    fuel: "Petrol",
    color: "Black",
    seats: 5,
    description:
      "Sporty executive sedan with premium interior finishes and confident handling.",
    features: ["Leather seats", "Navigation", "Parking sensors", "Heated seats"],
  },
];
